# Generated by Django 6.0.5 on 2026-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namme", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("instructions", models.TextField()),
                ("time", models.IntegerField()),
                ("level", models.CharField(max_length=10)),
            ],
        ),
    ]
