# Generated by Django 6.0.5 on 2026-05-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dj", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipe",
            old_name="namme",
            new_name="name",
        ),
    ]
