# Generated by Django 6.0.5 on 2026-05-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dj", "0002_rename_namme_receipe_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipe",
        ),
    ]
